### ISSUE TITLE
Cannot get MultiplexedConnection from get_multiplexed_tokio_connection().

### ISSUE THREAD

**Issue by weiby3** [mitsuhiko/redis-rs#367]
I copy the code from `bench_multiplexed_async_implicit_pipeline`, but the program cannot return from `get_multiplexed_tokio_connection()`. I have tried `bench_multiplexed_async_implicit_pipeline` and it worked.
Here are `Cargo.toml` and `main.rs`
```toml
[dependencies]
redis = { version = "0.16.0", features = ["aio", "tokio-rt-core", "tokio-comp"] }
tokio = { version = "0.2.22", features = ["rt-core", "macros", "time"] }
futures = "0.3.5"
```

```rust
use futures::{prelude::*, stream};
const TIMES: usize = 1024;
fn main() {
    let client = get_client();
    let mut runtime = current_thread_runtime();
    let con = runtime
        .block_on(client.get_multiplexed_tokio_connection())
        .unwrap();

    let cmds: Vec<_> = (0..TIMES)
        .map(|i| redis::cmd("SET").arg(format!("foo{}", i)).arg(i).clone())
        .collect();

    let mut connections = (0..TIMES)
        .map(|_| con.clone())
        .collect::<Vec<_>>();

    for _ in 0..TIMES {
        let () = runtime
            .block_on(async {
                cmds.iter()
                    .zip(&mut connections)
                    .map(|(cmd, con)| cmd.query_async(con))
                    .collect::<stream::FuturesUnordered<_>>()
                    .try_for_each(|()| async { Ok(()) })
                    .await
            })
            .unwrap();
    }
}
pub fn current_thread_runtime() -> tokio::runtime::Runtime {
    let mut builder = tokio::runtime::Builder::new();
    builder.enable_io();
    builder.basic_scheduler().build().unwrap()
}
fn get_client() -> redis::Client {
    redis::Client::open("redis://127.0.0.1:6379").unwrap()
}
```
